### ISSUE TITLE
Font Type and Background Color Change

### ISSUE THREAD

**Issue by mmeiers** [Rise-Vision/widget-text#50] opened 2015-08-18 15:03 UTC
This may be hard to replicate as this happens only sometimes. You really just need to play around with it. 

If I set a font type to a google font under the "more fonts" it will look fine in the widget settlings. Then  I will save and preview and notice the font is not correct and there is a white background.

When i go back to the settings this is what I see:
http://www.screencast.com/t/Arrbtaaqt

Notice the background is white which I did not change and the font is Oswald but it looks like its actually times roman. Occasionally I will go back in the settings and it will say arial even though I know Ive set it to a different font and saved.

**Comment by donnapep** [comment] 2016-02-10 14:09
Closing as I can't reproduce in the latest version of the Text Widget.

**Closed by donnapep** 2016-02-10 14:09 UTC

**Comment by mmeiers** [comment] 2016-02-10 14:44
@donnapep Yep agree should close these and open new ones if we notice anything different.
