### ISSUE TITLE
Uptime errors not published to user

### ISSUE THREAD

**Issue by alanclayton** [Rise-Vision/widget-text#141] opened 2020-08-21 17:51 UTC
The following uptime errors are being reported, but they are not being published to the User:

- E000000055

**Comment by stulees** [comment] 2020-08-27 15:08
@alanclayton As per discussed in [investigation doc](https://docs.google.com/document/d/1PpaVhujIbwcVwy1WB3qdLYvDqpaRDz5Ju9vsy58OjF4/edit), the proposed fix/improvement has been deployed with PR #142 . We can monitor Shared Schedule errors over next few days to observe any improvement. Should this issue be left open in the meantime or close now? Thanks

**Comment by alanclayton** [comment] 2020-08-27 16:10
@stulees it should stay open until resolved. Thanks

**Comment by olegrise** [comment] 2020-10-02 14:45
It seems that the reason for this issue is that Google Fonts URL(s) are blocked on some machines.

We had conversation with @stulees, @alanclayton, and @ByronDarlison this morning and decided that we just need to make sure that URLs are included into network requirements. After that Alan confirmed the network requirements article includes the URL for google fonts.

My understanding is this defect should remain open until we are informing the user and providing the correction as per when Uptime/Logging is finalized. @alanclayton please confirm. Thanks.

**Comment by ezequielc** [comment] 2021-09-09 20:55
@stulees Closing as per https://github.com/Rise-Vision/rise-twitter/issues/70#issuecomment-916420515. Thanks

**Closed by ezequielc** 2021-09-09 20:55 UTC
